server:
  port: 8888

spring:
  application:
    name: local-config-server
  profiles:
    active: native

#spring:
#  application:
#    name: local-config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: classpath:config/

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///C:/Spring_Boot_Try_out/TDD/temp