server:
  port: 8090
spring:
  application:
    name: auth-server-wt-db
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace