server:
  port: 8090
spring:
  application:
    name: auth-server-wt-db
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

config:
  oauth2:
    private-key: -----BEGIN RSA PRIVATE KEY----- MIIEowIBAAKCAQEAycCwsmO9s/V3R7qvVSHQdCeM815zG+IiSkXDw7mRBlyJM64d mgu9z0mn3SiGf5PodqvMSEYDALR/AH3evsUS+0Ohp/PDIFYrjPtrBhnvDlA5+63K tLVri/dc4/2dspc7hpz2ILYCPItInwz670jUVyqymdE+enTuQ/W6DTUP98OxKt5A 5q9E3uw2wfi9DIZ/il4+XaIJHbyGsnsKpxINwR8fIR52zG2GMRulRZzhijhrDu2x pbwpeDcAaMjzz2RYpTfEa20iSM+nUPzq8JbeooTgZVkF/mb3a9ZQgPo0auB0cMfJ HwSfFWfGSNoaz6RogmwaS13tFh/cw30fjcZ03QIDAQABAoIBAQCSWxxTbJOTVsBe 4oiKo2sKuB5B9gRe996ULqPi+lzAVqSZPvfuZhIdq3sAroNTTULXw6z/yPooqsdu 3eCWV3R7ngZJRkYI0TnqngB3fpyyr3RApURlby5DbQCPy814Xskpz/ekpyRcM1ZN OydWKmkPisPhXa+LOgQWfM2pAxNAUgUjwQrf/KF7D+WCSqE3L1yJIeqtC7iVjNJV QwQ1kG0rHjHf/aq7QJC9PXHzF/f7SHLvQkXUNwBEFEPVySph8YqCa98wsxMsu37F biWpb8K4i4s0CfchVEs+/XEzptKBhWkEXrlGOYgGKg1uJRff/BUyJUpA/NqbADkN FcbgRl2pAoGBAPVY33c6yJOfah8/+g7ooJKSVTCCJFXGG+8Q17HmW57/M3w0KcL+ jJY3u+O6jgYEeaeoq2TpNX9wdOX0zTrHka5V3AXzaPVG1UUyE5vTmblV4lcl9Za9 j+13Uuol/ONYYzg20RpPhjBF21wXSWCnwN8qsEhWZ341uJ99nf+4tdm/AoGBANKD P409G6NCn7cnGaOFx0F+1XV2/9cciebZ0J0J4G3xBMGTC148doDS7RvtloOgXWgQ xorc1HA5mKQ53bffTEgt38o/W2BjwsXMLPpsupF6AUwyr1pMvkmjevzlNEWv5UPX ckDOd2jr52ssLYTlLCX7ln29DXXYXWVUAeNk3MBjAoGAWLK5jzQ8QUpXplaNw4gM TREEJVZXZn8JqEMRh6o9I10lsth05J78Gm6pyamvILPLe3Z6CDBbe+gfCueWrpJp s3os4iXeoxXpkmuJNUOphpxrCJCbmdSMTRBfdHEpXNOegzsmG3n2jEslA8UTbRMY olWfh3ddUP6A8YALd+DCNacCgYBTycOwzsLCX5E8kAaHbIbbjcUehOfd0dEdnlKH PtgiSk0vUvyyXHR6X/naJN3EtD6ZXhv4R18S8AnOS+3w8qLlE8VANamEGxD6M4Mv hblYj+wWTRI4adVPcA9Su1Pr7M/fCdDC9KrYixTINoRDogfJcnL6xxWlcyHxY9eA j7PBqwKBgEaKmSBdIpYIwwjux0NEIx0WhtGQoJffXvWguKakemxdElJZPwhu4rpg yPoW/y5jBA9EKuKPP+DQLFTpoRlVJsR9W9YWW3o/mjwxhAuaEtzNTh3oWS+2/zbZ 1fIGh5XaqQDfo72V1VtZ7C4wRA1x6R8cIsEQtEgvG7Lc9CLgJ8Ck -----END RSA PRIVATE KEY-----
    public-key: -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAycCwsmO9s/V3R7qvVSHQ dCeM815zG+IiSkXDw7mRBlyJM64dmgu9z0mn3SiGf5PodqvMSEYDALR/AH3evsUS +0Ohp/PDIFYrjPtrBhnvDlA5+63KtLVri/dc4/2dspc7hpz2ILYCPItInwz670jU VyqymdE+enTuQ/W6DTUP98OxKt5A5q9E3uw2wfi9DIZ/il4+XaIJHbyGsnsKpxIN wR8fIR52zG2GMRulRZzhijhrDu2xpbwpeDcAaMjzz2RYpTfEa20iSM+nUPzq8Jbe ooTgZVkF/mb3a9ZQgPo0auB0cMfJHwSfFWfGSNoaz6RogmwaS13tFh/cw30fjcZ0 3QIDAQAB -----END PUBLIC KEY-----