server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chaminda202/Microservice-architecture-try-out
          search-paths:
            - 'local_git'